ERCTest/Models/ErrorViewModel.cs
using System;

namespace ERCTest.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ERCTest/Controllers/FilterController.cs
using ERCTest.Models;
using ERCTest.DAL.Models.EF;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using ERCTest.DAL.Models.ViewModels;
using ERCTest.DAL.Models.Entities;
using System.Net.Http;
using Newtonsoft.Json;
using System.Net.Http.Json;
using System.Text;

namespace ERCTest.Controllers
{
    public class FilterController : Controller
    {
        HttpClient httpClient;

        public FilterController()
        {
            HttpClientHandler clientHandler = new HttpClientHandler()
            {
                ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) => { return true; }
            };

            httpClient = new HttpClient(clientHandler);
        }

        public async Task<IActionResult> FilterByResidentsOnly()
        {
            var viewModel = await httpClient.GetFromJsonAsync<PersonalAccountViewModel>("https://localhost:44302/api/BLL/GetByResidentsOnly");

            return View("Index", viewModel);
        }

        public async Task<IActionResult> FilterByStartDate(PersonalAccountViewModel viewModel)
        {
            using var response = await httpClient.PostAsJsonAsync("https://localhost:44302/api/BLL/GetByStartDate", viewModel);
            PersonalAccountViewModel responseViewModel = await response.Content.ReadFromJsonAsync<PersonalAccountViewModel>();

            return View("Index", responseViewModel);
        }

        public async Task<IActionResult> FilterByNameResidents(PersonalAccountViewModel viewModel)
        {
            using var response = await httpClient.PostAsJsonAsync("https://localhost:44302/api/BLL/GetByResidentsName", viewModel);
            PersonalAccountViewModel responseViewModel = await response.Content.ReadFromJsonAsync<PersonalAccountViewModel>();

            return View("Index", responseViewModel);
        }

        public async Task<IActionResult> FilterByAdress(PersonalAccountViewModel viewModel)
        {
            using var response = await httpClient.PostAsJsonAsync("https://localhost:44302/api/BLL/GetByAdress", viewModel);
            PersonalAccountViewModel responseViewModel = await response.Content.ReadFromJsonAsync<PersonalAccountViewModel>();

            return View("Index", responseViewModel);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ERCTest/Controllers/HomeController.cs
using ERCTest.Models;
using ERCTest.DAL.Models.EF;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using ERCTest.DAL.Models.ViewModels;
using ERCTest.DAL.Models.Entities;
using System.Net.Http;
using Newtonsoft.Json;
using System.Net.Http.Json;
using System.Text;

namespace ERCTest.Controllers
{
    public class HomeController : Controller
    {
        HttpClient httpClient;

        public HomeController()
        {
            HttpClientHandler clientHandler = new HttpClientHandler() 
            { 
                ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) => { return true; } 
            };

            httpClient = new HttpClient(clientHandler);
        }

        public async Task<IActionResult> Index()
        {
            var viewModel = await httpClient.GetFromJsonAsync<PersonalAccountViewModel>("https://localhost:44302/api/DAL/GetAll");

            return View(viewModel);
        }

        public IActionResult CreateAccount()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateAccount(PersonalAccount personalAccount)
        {
            await httpClient.PostAsJsonAsync("https://localhost:44302/api/DAL/Create", personalAccount);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> EditAccount(int id, PersonalAccountViewModel viewModel)
        {
            var updateAcc = viewModel.PersonalAccounts.Where(x => x.Id == id).SingleOrDefault();
            await httpClient.PutAsJsonAsync("https://localhost:44302/api/DAL/Update", updateAcc);

            return NoContent();
        }

        public async Task<IActionResult> DeleteAccount(int id)
        {
            await httpClient.DeleteAsync($"https://localhost:44302/api/DAL/Delete/{id}");

            return RedirectToAction("Index");
        }
    }
}

ERCTest/Views/Home/CreateAccount.cshtml
@using ERCTest.DAL.Models.Entities
@using ERCTest.DAL.Models.ViewModels
@model PersonalAccount


<html>
    <head>
        <title>CreateAccount</title>
        <meta charset="UTF-8" />
    </head>

    <body>
        <h1>Добавить новый лицевой счёт</h1>
            <form id="form" class="shift" asp-action="CreateAccount" asp-controller="Home">

                <div class="startDate">
                    <label asp-for="StartDate">Дата начала действия</label>
                    <input type="date" asp-for="StartDate" required id="startDate"/>
                </div>

                <div class="EndDate">
                    <label asp-for="EndDate">Дата окончания действия</label>
                    <input type="date" asp-for="EndDate" required id="endDate"/>
                </div>

                <div>
                    <label asp-for="Area">Площадь помещения, кв.м</label>
                    <input type="text" asp-for="Area" required/>
                </div>

                <div>   
                    <label asp-for="Address">Адрес</label>
                    <input class="adress" type="text" asp-for="Address" required/>
                </div>

                <div> 
                @{
                    <label asp-for="Residents">Проживающие</label>
                    <button type="button" onclick="add_field()" id="addResident">Добавить проживающего</button>

                    for(var i = 0; i <= 5; i++)
                    {
                        <div class="residents">
                            <input type="hidden" asp-for="Residents[i].Surname" placeholder="Фамилия" required/>
                            <input type="hidden" asp-for="Residents[i].Name" placeholder="Имя" required/>
                            <input type="hidden" asp-for="Residents[i].Patronymic" placeholder="Отчество" required/>
                        </div>
                    }

                }
                </div>

                <div>
                    <input type="button" onclick="submitForm()" value="Добавить" class="enter" id="submitFormId"/>
                </div>
            </form>
    </body>
</html>

ERCTest/Views/Shared/Index.cshtml
@using ERCTest.DAL.Models.ViewModels
@model PersonalAccountViewModel

<div class="accounts">
    <div class="filters">   
        <div>
            <a type="button" asp-action="FilterByResidentsOnly" asp-controller="Filter" class="filterResidentsButton">Только ЛС с проживающими</a>
        </div>

        <form class="divFilter">
                <input type="submit" asp-action="FilterByStartDate" asp-controller="Filter" class="filterButton" value="Только открытые на указанную дату ЛС"/>
                <input asp-for="StartDate" type="date" class="filterInput" required/>
        </form>

        <form class="divFilter">
            <input type="submit" asp-action="FilterByNameResidents" asp-controller="Filter" class="filterButton" value="Поиск ЛС по ФИО проживающего"/>
            <input asp-for="Name" type="text" class="filterInput" required/>
        </form>

        <form class="divFilter">
            <input type="submit" asp-action="FilterByAdress" asp-controller="Filter" class="filterButton" value="Поиск по адресу"/>
            <input asp-for="Adress" type="text" class="filterInput" required/>
        </form>
    </div>

    <form asp-action="EditAccount" asp-controller="Home">
    @{
        for(int i = 0; i < Model.PersonalAccounts.Count(); i++)
        {
                    <div class="account">
                        <input type="hidden" asp-for="PersonalAccounts[i].Id" value="@Model.PersonalAccounts[i].Id" readonly/>

                        <div class="staticDiv">   
                            <label asp-for="PersonalAccounts[i].Number">Номер лицевого счёт:</label>
                            <input type="text" asp-for="PersonalAccounts[i].Number" value="@Model.PersonalAccounts[i].Number" readonly/>
                            <a class="detail">Подробнее</a>
                        </div>

                        <div class="inputDiv">   
                            <label asp-for="PersonalAccounts[i].StartDate" hidden class="label">Дата начала действия:</label>
                            <input asp-for="PersonalAccounts[i].StartDate" type="date" value="@Model.PersonalAccounts[i].StartDate" id="startDate" hidden readonly class="input"/>
                        </div>

                        <div class="inputDiv">   
                            <label asp-for="PersonalAccounts[i].EndDate" hidden class="label">Дата окончания действия:</label>
                            <input asp-for="PersonalAccounts[i].EndDate" type="date" value="@Model.PersonalAccounts[i].EndDate" id="endDate" hidden readonly class="input"/>
                        </div>

                        <div class="inputDiv">   
                            <label asp-for="PersonalAccounts[i].Area" hidden class="label">Площадь помещения, кв.м:</label>
                            <input asp-for="PersonalAccounts[i].Area" type="text" value="@Model.PersonalAccounts[i].Area" hidden readonly class="input"/>
                        </div>

                        <div class="inputDiv">   
                            <label asp-for="PersonalAccounts[i].StartDate" hidden class="label">Адрес:</label>
                            <input asp-for="PersonalAccounts[i].Address" type="text" value="@Model.PersonalAccounts[i].Address" hidden readonly class="input" id="adress"/>
                        </div>

                        <div class="inputDiv">   
                            <label asp-for="PersonalAccounts[i].Residents" hidden class="label">Проживающие</label>
                            @*<button type="button" onclick="add_field()" id="addResident" class="label" hidden disabled>Добавить проживающего</button>*@
                        </div>

                        <div class="inputDiv"> 
                        @{
                            if(@Model.PersonalAccounts[i].Residents != null)
                                for(var e = 0; e < @Model.PersonalAccounts[i].Residents.Count(); e++)
                                {
                                    <div class="residents">
                                        <input type="text" hidden asp-for="PersonalAccounts[i].Residents[e].Surname" placeholder="Фамилия" readonly class="resident"/>
                                        <input type="text" hidden asp-for="PersonalAccounts[i].Residents[e].Name" placeholder="Имя" readonly class="resident"/>
                                        <input type="text" hidden asp-for="PersonalAccounts[i].Residents[e].Patronymic" placeholder="Отчество" readonly class="resident"/>
                                    </div>
                                    <input type="hidden" asp-for="PersonalAccounts[i].Residents[e].Id"/>
                                    <input type="hidden" asp-for="PersonalAccounts[i].Residents[e].PersonalAccountId"/>
                                }
                        }
                        </div>

                        <input type="submit" 
                    asp-action="EditAccount" 
                    asp-controller="Home" 
                    class="editContent" 
                    value="Редактировать" 
                    asp-route-id="@Model.PersonalAccounts[i].Id"
                            hidden/>

                        <a type="button" 
                    asp-action="DeleteAccount" 
                    asp-controller="Home" 
                    class="deleteContent" 
                    asp-route-id="@Model.PersonalAccounts[i].Id" 
                            hidden>Удалить </a>
                    </div>
        }
    }
    </form>
</div>

ERCTest/Views/Shared/_Layout.cshtml
@using ERCTest.DAL.Controllers;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ERCTest</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="CreateAccount">Создать ЛС</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/index.js" asp-append-version="true"></script>
    <script src="~/js/CreateAccount.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>